---
- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true

  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: true
    - name: NGINX | Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present
      notify:
        - Restart nginx
    - name: NGINX | Create NGINX config file from template
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify:
        - Reload nginx
      tags:
        - nginx-configuration
  vars:
    nginx_listen_port: 8080
  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
