# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "nginx",
        :net => [
           ["192.168.11.150",  2, "255.255.255.0", "mynet"],
        ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      # Общие настройки сети, которые подходят обоим провайдерам
      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", 
          ip: ipconf[0], 
          netmask: ipconf[2], 
          virtualbox__intnet: ipconf[3],
          libvirt__network_name: ipconf[3],
          libvirt__forward_mode: "none"
      end

      # Специфичные настройки для VirtualBox (включая адаптер)
      box.vm.provider "virtualbox" do |v, override|
        v.memory = 768
        v.cpus = 1
        
        # Дописываем параметр adapter ТОЛЬКО для VirtualBox
        boxconfig[:net].each do |ipconf|
          override.vm.network "private_network", ip: ipconf[0], adapter: ipconf[1]
        end
      end

      # Специфичные настройки для Libvirt
      box.vm.provider "libvirt" do |v|
        v.memory = 768
        v.cpus = 1
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end

